#!/usr/bin/env bash
# Regenerates third_party/flatlaf-<version>-atomchat.jar from a FlatLaf release.
#
# This is a maintenance action, not part of any build: the relocated jar is
# committed, so CI and every developer build stay offline and deterministic.
# Run it when bumping flatlaf_version:
#
#   tools/relocate-flatlaf.sh <path-to-flatlaf.jar> [version]
#
# The tool needs ASM; it is looked up in the Gradle cache first (any version with
# asm-commons will do), then in $ASM_JARS.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOL_DIR="$REPO_ROOT/tools/flatlaf-relocate"

# Native Windows tools want C:/... paths; MSYS wants /c/... ones. Keep the
# conversion in one place instead of fighting the shell's automatic rewriting.
winpath() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}

if [ $# -lt 1 ]; then
  echo "usage: $0 <path-to-flatlaf.jar> [version]" >&2
  exit 2
fi
IN=$1
VERSION=${2:-}

if [ -z "$VERSION" ]; then
  # flatlaf-3.7.2.jar -> 3.7.2
  VERSION=$(basename "$IN" | sed -E 's/^flatlaf-(.+)\.jar$/\1/')
fi
# A local Maven layout, not a bare jar: Fabric's `include` refuses to nest an
# artifact that is "not a module component and has no capabilities", and Forge's
# JarJar wants real coordinates in its metadata.json.
GROUP=com.atom.chat.bundled
ARTIFACT=flatlaf-atomchat
SHADED_PKG=com.atom.chat.shaded.flatlaf
REPO="$REPO_ROOT/third_party/maven"
OUTDIR_MAVEN="$REPO/${GROUP//./\/}/$ARTIFACT/$VERSION"
OUT="$OUTDIR_MAVEN/$ARTIFACT-$VERSION.jar"
POM="$OUTDIR_MAVEN/$ARTIFACT-$VERSION.pom"

find_asm() {
  if [ -n "${ASM_JARS:-}" ]; then echo "$ASM_JARS"; return; fi
  local cache="$HOME/.gradle/caches/modules-2/files-2.1/org.ow2.asm"
  local v a b c
  # Highest version that has all three jars present: mixing versions across
  # asm / asm-commons / asm-tree is what breaks ASM at runtime.
  for v in $(ls "$cache/asm" 2>/dev/null | sort -V -r); do
    a=$(find "$cache/asm/$v" -name 'asm-*.jar' ! -name '*sources*' 2>/dev/null | head -1)
    b=$(find "$cache/asm-commons/$v" -name 'asm-commons-*.jar' ! -name '*sources*' 2>/dev/null | head -1)
    c=$(find "$cache/asm-tree/$v" -name 'asm-tree-*.jar' ! -name '*sources*' 2>/dev/null | head -1)
    if [ -n "$a" ] && [ -n "$b" ] && [ -n "$c" ]; then
      # Drive-letter form: javac/java are native Windows programs and MSYS would
      # otherwise rewrite (or mangle) the ';'-joined classpath.
      echo "$(winpath "$a");$(winpath "$b");$(winpath "$c")"
      return
    fi
  done
}

ASM=$(find_asm)
if [ -z "$ASM" ] || [ "$(echo "$ASM" | tr ';' '\n' | wc -l)" -lt 3 ]; then
  echo "Could not locate asm / asm-commons / asm-tree." >&2
  echo "Set ASM_JARS='asm.jar;asm-commons.jar;asm-tree.jar' and retry." >&2
  exit 1
fi

OUTDIR=$(mktemp -d)
trap 'rm -rf "$OUTDIR"' EXIT

echo "compiling Relocate.java"
javac -nowarn -encoding UTF-8 -cp "$ASM" -d "$(winpath "$OUTDIR")" "$(winpath "$TOOL_DIR/Relocate.java")"

mkdir -p "$(dirname "$OUT")"
echo "relocating $IN -> $OUT"
java -cp "$(winpath "$OUTDIR");$ASM" Relocate "$(winpath "$IN")" "$(winpath "$OUT")"

cat > "$POM" <<POMEOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>$GROUP</groupId>
  <artifactId>$ARTIFACT</artifactId>
  <version>$VERSION</version>
  <packaging>jar</packaging>
  <name>FlatLaf $VERSION (relocated for AtomChat)</name>
  <description>
    FlatLaf $VERSION with com.formdev.flatlaf relocated to $SHADED_PKG.
    Bundled so another mod shipping the public package cannot win the class
    loading race. Licensed Apache-2.0; see THIRD_PARTY_NOTICES.md.
    Generated by tools/relocate-flatlaf.sh - do not edit by hand.
  </description>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
</project>
POMEOF

ls -l "$OUT" "$POM"

# Forge's JarJar only accepts a Maven RANGE, and a range makes Gradle ask the
# repository for its version list — for a directory repository that listing is
# maven-metadata.xml. Without it the range resolves nowhere.
META_DIR="$OUTDIR_MAVEN/.."
META_DIR=$(cd "$META_DIR" && pwd)
{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<metadata>'
  echo "  <groupId>$GROUP</groupId>"
  echo "  <artifactId>$ARTIFACT</artifactId>"
  echo '  <versioning>'
  echo "    <latest>$VERSION</latest>"
  echo "    <release>$VERSION</release>"
  echo '    <versions>'
  for v in $(ls "$META_DIR" 2>/dev/null | grep -E '^[0-9]' | sort -V); do
    echo "      <version>$v</version>"
  done
  echo '    </versions>'
  echo "    <lastUpdated>$(date +%Y%m%d%H%M%S)</lastUpdated>"
  echo '  </versioning>'
  echo '</metadata>'
} > "$META_DIR/maven-metadata.xml"

echo "sha256: $(sha256sum "$OUT" | cut -d' ' -f1)"
echo
echo "Platform builds reference ${GROUP}:${ARTIFACT}:\${flatlaf_version} via gradle/atomchat-layers.gradle."
